#pragma once

static const char INDEX_HTML[] = R"HTML(
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" href="/favicon.ico">
<title>Typheye Car</title>
<style>
:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,"Noto Sans SC",sans-serif;color:#172033;background:#f6f7f9;--bg:#f6f7f9;--card:#fff;--panel:#eef2f6;--line:#d9e0ea;--muted:#667085;--text:#172033;--blue:#2563eb}
:root.dark{color:#e5e7eb;background:#0e1117;--bg:#0e1117;--card:#151a23;--panel:#1e2633;--line:#303847;--muted:#9ca3af;--text:#e5e7eb;--blue:#60a5fa}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}main{max-width:1180px;margin:0 auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.brand h1{margin:0 0 6px;font-size:28px}.brand p{margin:0;color:var(--muted)}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:18px;box-shadow:0 1px 2px #1018280a}.status{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.metric{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:12px;min-width:0}.metric small{display:block;color:var(--muted);margin-bottom:6px}.metric b{font-size:18px;overflow-wrap:anywhere}
.layout{display:grid;grid-template-columns:1.15fr .85fr;gap:16px}.head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px}.head h2,.head h3{font-size:20px;margin:0}.muted{color:var(--muted)}.pill{display:inline-flex;align-items:center;gap:6px;padding:4px 9px;border-radius:999px;font-weight:700;font-size:12px}.ok{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.bad{background:#fee2e2;color:#991b1b}
.dot{display:inline-block;width:10px;height:10px;border-radius:50%;background:#22c55e;box-shadow:0 0 10px #22c55e}.dot.wait{background:#f59e0b;box-shadow:0 0 10px #f59e0b;animation:pulse 1.6s infinite}.device,.net,.saved{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line)}.device:last-child,.net:last-child,.saved:last-child{border-bottom:0}.device b,.net b,.saved b{font-size:15px}.meta{font-size:13px;color:var(--muted);margin-top:5px;overflow-wrap:anywhere}
.settings{display:grid;gap:10px}.row{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:13px 0;border-bottom:1px solid var(--line)}.row:last-child{border-bottom:0}.switch{position:relative;width:48px;height:28px;flex:0 0 auto}.switch input{display:none}.slider{position:absolute;inset:0;border-radius:999px;background:#d0d5dd;cursor:pointer;transition:.18s}.slider:before{content:"";position:absolute;width:22px;height:22px;left:3px;top:3px;background:white;border-radius:50%;box-shadow:0 1px 3px #0002;transition:.18s}.switch input:checked+.slider{background:var(--blue)}.switch input:checked+.slider:before{transform:translateX(20px)}
button,select,input{font:inherit}button{border:0;border-radius:7px;padding:9px 12px;font-weight:700;cursor:pointer;white-space:nowrap}.primary{background:var(--blue);color:#fff}.ghost{background:var(--panel);color:var(--text)}.softDanger{background:var(--panel);color:#b42318}.danger{background:#fee2e2;color:#991b1b}.select{border:1px solid var(--line);border-radius:7px;background:var(--card);color:var(--text);padding:8px 10px;max-width:170px}.iconBtn{width:38px;height:38px;padding:0;display:grid;place-items:center;background:var(--panel);border:1px solid var(--line)}.binIcon{display:grid;grid-template-columns:repeat(8,2px);grid-auto-rows:2px;gap:1px}.binIcon i{width:2px;height:2px;background:var(--text);opacity:.18}.binIcon i.on{opacity:1}
.modal{position:fixed;inset:0;background:#0f172a80;display:none;align-items:center;justify-content:center;padding:18px;z-index:10}.modal.show{display:flex}.box{width:min(560px,100%);max-height:86vh;overflow:auto;background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px}.form{display:grid;gap:10px}.form label{font-size:13px;color:var(--muted)}.form input{width:100%;border:1px solid var(--line);border-radius:7px;padding:10px;background:var(--card);color:var(--text)}.actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.hint{font-size:12px;color:var(--muted);margin-top:10px}.loader{display:flex;align-items:center;gap:10px;color:var(--muted);padding:14px 0}.spin{width:18px;height:18px;border:2px solid #d0d5dd;border-top-color:var(--blue);border-radius:50%;animation:spin .75s linear infinite}
@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}@media(max-width:820px){main{padding:14px}.status,.layout{grid-template-columns:1fr}.top{flex-direction:row}.card{padding:15px}.row{align-items:flex-start}.device,.net,.saved{grid-template-columns:1fr}.device .pill{width:max-content}}
</style>
</head>
<body>
<main>
  <div class="top"><div class="brand"><h1>Typheye Car</h1><p data-i="subtitle"></p></div><button class="iconBtn" id="themeBtn" aria-label="theme"></button></div>
  <section class="status" id="status"></section>
  <section class="layout">
    <div class="card"><div class="head"><h2 data-i="onlineDevices"></h2><span class="muted" id="devCount"></span></div><div id="devices"></div></div>
    <div class="card"><div class="head"><h2 data-i="settings"></h2></div><div class="settings">
      <div class="row"><b data-i="shareWlan"></b><label class="switch"><input id="share" type="checkbox"><span class="slider"></span></label></div>
      <div class="row"><b data-i="scanNetworks"></b><button class="ghost" id="scanBtn"></button></div>
      <div class="row"><b data-i="savedNetworks"></b><button class="ghost" id="savedBtn" data-i="view"></button></div>
      <div class="row"><b data-i="breathLed"></b><label class="switch"><input id="led" type="checkbox"><span class="slider"></span></label></div>
      <div class="row"><b data-i="language"></b><select id="lang" class="select"><option value="auto" id="autoLangOpt">Auto</option><option value="zh">中文</option><option value="en">English</option></select></div>
    </div><p class="hint" data-i="hint"></p></div>
  </section>
</main>
<div class="modal" id="scanModal"><div class="box"><div class="head"><h3 data-i="nearby"></h3><button class="ghost" onclick="closeModal('scanModal')">x</button></div><div id="scanList"></div></div></div>
<div class="modal" id="savedModal"><div class="box"><div class="head"><h3 data-i="savedNetworks"></h3><button class="ghost" onclick="closeModal('savedModal')">x</button></div><div id="savedList"></div></div></div>
<div class="modal" id="editModal"><div class="box"><h3 id="editTitle"></h3><div class="form"><label>SSID</label><input id="ssid" placeholder="SSID"><label data-i="password"></label><input id="pass" type="password" placeholder="Password"></div><div class="actions"><button class="ghost" onclick="closeModal('editModal')" data-i="cancel"></button><button class="danger" id="delBtn" data-i="delete"></button><button class="primary" id="saveBtn" data-i="save"></button></div></div></div>
<script>
const I={zh:{subtitle:'车载网络与设备状态',onlineDevices:'在线设备',settings:'设置',shareWlan:'共享 WLAN',scanNetworks:'扫描周围网络',savedNetworks:'已保存网络',breathLed:'启用呼吸灯',language:'语言',hint:'共享 WLAN 关闭时热点仍可访问设置页，但不会转发外网。',view:'查看',disconnect:'断开',edit:'编辑',nearby:'周围网络',cancel:'取消',delete:'删除',save:'保存',connect:'连接',password:'密码',openNet:'开放网络',online:'在线',none:'暂无设备',empty:'暂无已保存网络',state:'状态',nat:'NAT',ap:'热点',enabled:'已启用',disabled:'未启用',connected:'已连接',notConnected:'未连接',running:'运行中',waiting:'等待设备',editing:'编辑',loading:'正在扫描...',scanError:'扫描失败'},en:{subtitle:'Vehicle network and device status',onlineDevices:'Online devices',settings:'Settings',shareWlan:'Share WLAN',scanNetworks:'Scan nearby networks',savedNetworks:'Saved networks',breathLed:'Breathing LED',language:'Language',hint:'When WLAN sharing is off, the hotspot still serves this page but does not route Internet traffic.',view:'View',disconnect:'Disconnect',edit:'Edit',nearby:'Nearby networks',cancel:'Cancel',delete:'Delete',save:'Save',connect:'Connect',password:'Password',openNet:'Open network',online:'Online',none:'No clients connected',empty:'No saved networks',state:'State',nat:'NAT',ap:'Hotspot',enabled:'Enabled',disabled:'Disabled',connected:'Connected',notConnected:'Not connected',running:'Running',waiting:'Waiting',editing:'Edit',loading:'Scanning...',scanError:'Scan failed'}};
const SUN=[0,0,1,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,1,1,1,1,0,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,1,0,1,1,1,1,0,1,0,0,0,1,1,0,0,0,0,0,1,0,0,1,0,0],MOON=[0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,0];
let S={},editSlot=-1,manualLang=null,theme=localStorage.getItem('theme')||'auto';const $=id=>document.getElementById(id);function systemZh(){return (navigator.language||'en').toLowerCase().startsWith('zh')}function currentLang(){let l=manualLang||S.settings?.lang||'auto';return l==='auto'?(systemZh()?'zh':'en'):l}function t(k){return (I[currentLang()]&&I[currentLang()][k])||k}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function mask(s){return s?'*'.repeat(String(s).length):'-'}function setTheme(v){theme=v;localStorage.setItem('theme',theme);let dark=theme==='dark'||(theme==='auto'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.classList.toggle('dark',dark);let bits=dark?SUN:MOON;$('themeBtn').innerHTML='<span class="binIcon">'+bits.map(b=>`<i class="${b?'on':''}"></i>`).join('')+'</span>'}
function tr(){document.documentElement.lang=currentLang();$('autoLangOpt').textContent=systemZh()?'跟随系统':'Auto';document.querySelectorAll('[data-i]').forEach(e=>e.textContent=t(e.dataset.i));renderStaticState()}function pill(ok,txt){return `<span class="pill ${ok?'ok':'bad'}">${txt}</span>`}function renderStaticState(){let connected=!!S.sta?.connected;$('scanBtn').textContent=connected?t('disconnect'):t('view');$('scanBtn').className=connected?'softDanger':'ghost'}function render(){tr();$('share').checked=!!S.settings?.share;$('led').checked=!!S.settings?.led;$('lang').value=S.settings?.lang||'auto';$('status').innerHTML=`<div class="metric"><small>${t('state')}</small><b><span class="dot ${S.allSpecial?'':'wait'}"></span> ${S.allSpecial?t('running'):t('waiting')}</b></div><div class="metric"><small>${t('ap')}</small><b>${esc(S.ap?.ip||'-')}</b><div class="muted">${esc(S.ap?.ssid||'-')}</div></div><div class="metric"><small>WLAN</small><b>${S.sta?.connected?t('connected'):t('notConnected')}</b><div class="muted">${esc(S.sta?.ssid||'-')}</div></div><div class="metric"><small>${t('nat')}</small><b>${S.sta?.nat?t('enabled'):t('disabled')}</b><div class="muted">${esc(S.temp)} C / ${esc(S.mem)}%</div></div>`;let dev=(S.devices||[]).filter(d=>d.online);$('devCount').textContent=`${dev.length}/${S.ap?.max||0}`;$('devices').innerHTML=dev.length?dev.map(d=>`<div class="device"><div><b>${esc(d.name)}</b><div class="meta">${esc(d.mac)} · ${esc(d.ip||'-')}</div></div>${pill(true,t('online'))}</div>`).join(''):`<p class="muted">${t('none')}</p>`}
async function load(){S=await fetch('/api/state').then(r=>r.json());manualLang=null;render()}async function saveSettings(){manualLang=$('lang').value;await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`share=${$('share').checked?1:0}&led=${$('led').checked?1:0}&lang=${encodeURIComponent($('lang').value)}`});await load()}$('share').onchange=saveSettings;$('led').onchange=saveSettings;$('lang').onchange=()=>{manualLang=$('lang').value;tr();saveSettings()};$('themeBtn').onclick=()=>setTheme(document.documentElement.classList.contains('dark')?'light':'dark');matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>theme==='auto'&&setTheme('auto'));
function closeModal(id){$(id).classList.remove('show')}function openEdit(slot,ssid='',pass=''){$('editTitle').textContent=t('editing');editSlot=slot;$('ssid').value=ssid;$('pass').value=pass;$('delBtn').style.display=slot>=0?'inline-block':'none';$('editModal').classList.add('show')}window.openEdit=openEdit;window.closeModal=closeModal;$('saveBtn').onclick=async()=>{await fetch('/api/wifi',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`action=save&slot=${editSlot}&ssid=${encodeURIComponent($('ssid').value)}&password=${encodeURIComponent($('pass').value)}`});closeModal('editModal');closeModal('savedModal');await load()};$('delBtn').onclick=async()=>{await fetch('/api/wifi',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`action=delete&slot=${editSlot}`});closeModal('editModal');closeModal('savedModal');await load()};
$('scanBtn').onclick=async()=>{if(S.sta?.connected){await fetch('/api/disconnect',{method:'POST'});await load();return}$('scanModal').classList.add('show');$('scanList').innerHTML=`<div class="loader"><span class="spin"></span>${t('loading')}</div>`;let a=await fetch('/api/scan').then(r=>r.json());if(a.error){$('scanList').innerHTML=`<p class="muted">${t('scanError')}: ${esc(a.error)}</p>`;return}let seen=new Set(),nets=[];for(const n of a.networks||[]){let key=(n.ssid||'').trim();if(!key||seen.has(key))continue;seen.add(key);nets.push(n)}$('scanList').innerHTML=nets.length?nets.map((n,i)=>`<div class="net"><div><b>${esc(n.ssid)}</b><div class="meta">${esc(n.rssi)} dBm · ${n.open?t('openNet'):'WPA'}</div></div><button class="primary" data-idx="${i}">${t('connect')}</button></div>`).join(''):`<p class="muted">-</p>`;$('scanList').querySelectorAll('button').forEach(b=>b.onclick=()=>openEdit(-1,nets[+b.dataset.idx].ssid,''))};$('savedBtn').onclick=()=>{$('savedModal').classList.add('show');let p=S.profiles||[];$('savedList').innerHTML=p.length?p.map((x,i)=>`<div class="saved"><div><b>${esc(x.ssid)}</b><div class="meta">${t('password')}: ${mask(x.pass)}</div></div><button class="ghost" data-idx="${i}">${t('edit')}</button></div>`).join(''):`<p class="muted">${t('empty')}</p>`;$('savedList').querySelectorAll('button').forEach(b=>{let p=S.profiles[+b.dataset.idx];b.onclick=()=>openEdit(p.slot,p.ssid,p.pass)})};setTheme(theme);setInterval(load,3000);load();
</script>
</body>
</html>
)HTML";
